name: Python application test with Github Actions
on:
  push:
    branches: 
      - main
    # paths:
    #   - 'consumer/**'
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - uses: actions/checkout@v2
    
    # Setting up the Python
    - name: Set up Python 3.10.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.10
    
    # Installing all the dependencies
    - name: Install dependencies
      run: |
        make install
        
    - name: Test Consumer Interaction and Generate PACT file
      run: |
        version=${GITHUB_SHA::8} make test_consumer_interaction
    
    - name: Check file status
      run: |
        ls ${PWD}/pacts
        
    - name: Publish the Contract to Pact Broker
      uses: docker://pactfoundation/pact-cli
      with:
        args: |
            pact-broker publish
        
    - name: Deploy to test
      run: |
        # Placeholder for deploy

    - name: Tag the contract with Test after deployment
      run: |
        version=${GITHUB_SHA::8} make tag_consumer_contract_as_deployed
