name: Python application test with Github Actions
on:
  push:
    branches: 
      - main
    # paths:
    #   - 'consumer/**'
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Install pact-broker cli
      run: |
        sudo apt-get update && apt-get install -y build-essential git gcc
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/h2s/.bashrc
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew doctor
        brew tap pact-foundation/pact-ruby-standalone
        brew install pact-ruby-standalone

    # Checkout repository
    - uses: actions/checkout@v2
    
    # Setting up the Python
    - name: Set up Python 3.10.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.10
    
    # Installing all the dependencies
    - name: Install dependencies
      run: |
        make install
        
    - name: Test Consumer Interaction and Generate PACT file
      run: |
        version=${GITHUB_SHA::8} make test_consumer_interaction
        
    - name: Publish the Contract to Pact Broker
      run: |
        version=${GITHUB_SHA::8} make publish_contract
        
    - name: Deploy to test
      run: |
        # Placeholder for deploy

    - name: Tag the contract with Test after deployment
      run: |
        version=${GITHUB_SHA::8} make tag_consumer_contract_as_deployed
